# Merge the dataset of the indian paper :

1. Imports

In [15]:
import numpy as np
import pandas as pd

2. Montage Google Drive

In [16]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

3. Chemins des fichiers

In [17]:
csv_path_slope     = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/grid_with_fire_and_slope.csv"
csv_path_aspect    = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/grid_with_fire_aspect.csv"
csv_path_twi       = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/grid_with_fire_twi.csv"
csv_path_ndvi      = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/grid_with_fire_ndvi.csv"
csv_path_lst       = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/grid_with_LST.csv"
csv_path_distances = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/distances_grille_portugal.csv"
csv_path_elevation = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/elevation.csv"
output_csv_path    = "/content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/datasetPaperIndian.csv"

4. Chargement des CSV

In [18]:
df_slope     = pd.read_csv(csv_path_slope)
df_aspect    = pd.read_csv(csv_path_aspect)
df_twi       = pd.read_csv(csv_path_twi)
df_ndvi      = pd.read_csv(csv_path_ndvi)
df_lst       = pd.read_csv(csv_path_lst)
df_distances = pd.read_csv(csv_path_distances)
df_elevation = pd.read_csv(csv_path_elevation)

5. Aperçu des données

In [19]:
print("--- Slope ---")
display(df_slope.head(5))

print("--- Aspect ---")
display(df_aspect.head(5))

print("--- TWI ---")
display(df_twi.head(5))

print("--- NDVI ---")
display(df_ndvi.head(5))

print("--- LST ---")
display(df_lst.head(5))

print("--- Distances ---")
display(df_distances.head(5))

print("--- Élévation ---")
display(df_elevation.head(5))

--- Slope ---

    latitude  longitude  landcover  in_fire  dist_fire_km  mean_slope
0  36.987823  -7.963676        210        0     17.197693    0.571321
1  36.994129  -8.952213        110        0     23.004464    2.499209
2  36.996850  -7.974890        210        0     16.054264    1.402498
3  37.003139  -8.952309        210        0     22.375234    2.263847
4  37.003216  -8.941076        210        0     21.596848    2.697602

--- Aspect ---

    latitude  longitude  landcover  in_fire  dist_fire_km  mean_aspect
0  36.987823  -7.963676        210        0     17.197693   196.846283
1  36.994129  -8.952213        110        0     23.004464   178.080078
2  36.996850  -7.974890        210        0     16.054264   179.751862
3  37.003139  -8.952309        210        0     22.375234   290.926086
4  37.003216  -8.941076        210        0     21.596848   171.431244

--- TWI ---

    latitude  longitude  landcover  in_fire  dist_fire_km  mean_twi
0  36.987823  -7.963676        210        0     17.197693  6.447956
1  36.994129  -8.952213        110        0     23.004464  3.489216
2  36.996850  -7.974890        210        0     16.054264  7.057358
3  37.003139  -8.952309        210        0     22.375234  3.493453
4  37.003216  -8.941076        210        0     21.596848  4.360210

--- NDVI ---

,latitude,longitude,landcover,in_fire,dist_fire_km,ndvi_raw,ndvi_final
0,36.987823,-7.963676,210,0,17.197693,0.686275,0.686275
1,36.994129,-8.952213,110,0,23.004464,0.866667,0.866667
2,36.996850,-7.974890,210,0,16.054264,0.889725,0.889725
3,37.003139,-8.952309,210,0,22.375234,0.866667,0.866667
4,37.003216,-8.941076,210,0,21.596848,0.918118,0.918118

--- LST ---

    latitude  longitude  landcover  in_fire  dist_fire_km  mean_LST_celsius
0  36.987823  -7.963676        210        0     17.197693         21.902494
1  36.994129  -8.952213        110        0     23.004464         15.699432
2  36.996850  -7.974890        210        0     16.054264         22.155281
3  37.003139  -8.952309        210        0     22.375234         16.453320
4  37.003216  -8.941076        210        0     21.596848         18.861568

--- Distances ---

,latitude,longitude,landcover,dist_residentiel_m,dist_route_m,dist_eau_m
0,36.987823,-7.963676,210,1846.893734,471.899104,0.000000
1,36.994129,-8.952213,110,1447.688717,170.582454,1815.680669
2,36.996850,-7.974890,210,457.222141,122.542919,0.000000
3,37.003139,-8.952309,210,715.827701,364.845213,1174.857886
4,37.003216,-8.941076,210,293.616377,242.791353,465.451046

--- Élévation ---

   longitude   latitude  Elevation
0  -7.963676  36.987823        0.0
1  -8.952213  36.994129        0.0
2  -7.974890  36.996850        0.0
3  -8.952309  37.003139        0.0
4  -8.941076  37.003216        0.0

6. Fusion des datasets

In [20]:
# Base : Slope
df_final = df_slope.copy()

# + TWI
df_final = pd.merge(df_final,
                    df_twi[['latitude', 'longitude', 'mean_twi']],
                    on=['latitude', 'longitude'], how='left')

# + Aspect
df_final = pd.merge(df_final,
                    df_aspect[['latitude', 'longitude', 'mean_aspect']],
                    on=['latitude', 'longitude'], how='left')

# + NDVI
df_final = pd.merge(df_final,
                    df_ndvi[['latitude', 'longitude', 'ndvi_final']],
                    on=['latitude', 'longitude'], how='left')

# + LST
df_final = pd.merge(df_final,
                    df_lst[['latitude', 'longitude', 'mean_LST_celsius']],
                    on=['latitude', 'longitude'], how='left')

# + Distances (routes, résidentiel)
df_final = pd.merge(df_final,
                    df_distances[['latitude', 'longitude', 'dist_residentiel_m', 'dist_route_m']],
                    on=['latitude', 'longitude'], how='left')

# + Élévation
df_final = pd.merge(df_final,
                    df_elevation[['latitude', 'longitude', 'Elevation']],
                    on=['latitude', 'longitude'], how='left')

7. Aperçu du dataset final

In [21]:
print(f"Dimensions : {df_final.shape}")
print(f"Colonnes   : {list(df_final.columns)}")
display(df_final.head(5))

Dimensions : (89198, 13)
Colonnes   : ['latitude', 'longitude', 'landcover', 'in_fire', 'dist_fire_km', 'mean_slope', 'mean_twi', 'mean_aspect', 'ndvi_final', 'mean_LST_celsius', 'dist_residentiel_m', 'dist_route_m', 'Elevation']

,latitude,longitude,landcover,in_fire,dist_fire_km,mean_slope,mean_twi,mean_aspect,ndvi_final,mean_LST_celsius,dist_residentiel_m,dist_route_m,Elevation
0,36.987823,-7.963676,210,0,17.197693,0.571321,6.447956,196.846283,0.686275,21.902494,1846.893734,471.899104,0.0
1,36.994129,-8.952213,110,0,23.004464,2.499209,3.489216,178.080078,0.866667,15.699432,1447.688717,170.582454,0.0
2,36.996850,-7.974890,210,0,16.054264,1.402498,7.057358,179.751862,0.889725,22.155281,457.222141,122.542919,0.0
3,37.003139,-8.952309,210,0,22.375234,2.263847,3.493453,290.926086,0.866667,16.453320,715.827701,364.845213,0.0
4,37.003216,-8.941076,210,0,21.596848,2.697602,4.360210,171.431244,0.918118,18.861568,293.616377,242.791353,0.0

8. Sauvegarde

In [22]:
df_final.to_csv(output_csv_path, index=False)
print(f"Dataset sauvegardé : {output_csv_path}")

Dataset sauvegardé : /content/gdrive/MyDrive/Projet big data dossier organisé /dataTraiter/datasetPaperIndian.csv